### ISSUE TITLE
Adding typescript

### ISSUE THREAD

**Issue by mehanalavimajd** [applecakejs/applecake#2]

**Comment by mehanalavimajd** [comment]
I think it's better to use Typescript instead of js .

**Comment by adabadadudu** [comment]
Unfortunately , I don't know about TypeScript but `.ts` compiles to `.js` so it's will translate to `.js`  .
but overall good .

**Comment by mehanalavimajd** [comment]
ok I have made all of the js files to ts file but if you want to send a PR you can send it to js and i will change it to ts . thanks
