### ISSUE TITLE
Import statement isn't working

### ISSUE THREAD

**Issue by mehanalavimajd** [applecakejs/applecake#3]
I added this to Render function: 
```js
export default function render ...
```
And made a test script :
```js
import render from "../dist/applecake.js"
```
But it make a error:
`Uncaught SyntaxError: Cannot use import statement outside a module`
@amirghazi87 and @PooiaFerdowsi do you know how to fix it ?

**Comment by adabadadudu** [comment]
can you add directory structure ? (use `tree` command)

**Comment by mehanalavimajd** [comment]
.
├── CONTRIBUTING.md
├── dist
│   ├── applecake.js
│   ├── applecake.js.map
│   └── typescript
│       └── applecake.ts
├── distpacker.js
├── docs
│   ├── 01-basics
│   │   ├── 1.installation.md
│   │   └── 2.CRH.md
│   ├── 02-Rendering
│   │   ├── 1.components.md
│   │   └── 2.Render&insert.md
│   └── 03-IdManager
│       └── 01.edit.md
├── images
│   ├── CRH.png
│   └── first-view.PNG
├── lib
│   ├── ID
│   │   ├── Manager
│   │   │   └── idmanager.ts
│   │   └── Select
│   │       └── idselector.ts
│   ├── Insert
│   │   └── insert.ts
│   └── Render
│       └── render.ts
├── LICENSE
├── Makefile
├── node_modules
│   ├── ansi-styles
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── license
│   │   ├── package.json
│   │   └── readme.md
│   ├── chalk
│   │   ├── index.d.ts
│   │   ├── license
│   │   ├── package.json
│   │   ├── readme.md
│   │   └── source
│   │       ├── index.js
│   │       ├── templates.js
│   │       └── util.js
│   ├── color-convert
│   │   ├── CHANGELOG.md
│   │   ├── conversions.js
│   │   ├── index.js
│   │   ├── LICENSE
│   │   ├── package.json
│   │   ├── README.md
│   │   └── route.js
│   ├── color-name
│   │   ├── index.js
│   │   ├── LICENSE
│   │   ├── package.json
│   │   └── README.md
│   ├── has-flag
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── license
│   │   ├── package.json
│   │   └── readme.md
│   └── supports-color
│       ├── browser.js
│       ├── index.js
│       ├── license
│       ├── package.json
│       └── readme.md
├── package.json
├── package-lock.json
├── packer.js
├── README.md
├── test
│   ├── h.html
│   └── h.js
├── TODO.md
└── tsconfig.json
thats it @PooiaFerdowsi

**Comment by adabadadudu** [comment]
`h.html` and `h.js` are you file ??

I think you should remove `test` directory and put your codes in root of your dir structure

[it's maybe help](https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import)

**Comment by mehanalavimajd** [comment]
Ok let me test it

**Comment by mehanalavimajd** [comment]
I put h.js and h.html in root of directory but It again make that error .
and I have added this:
```html
<script type="module" src="h.js"></script>
```
after adding "type=module" there is no error but nothing will happen i mean  nothing will be rendered on browser @PooiaFerdowsi .

**Comment by mehanalavimajd** [comment]
I think we should add a `wont'fix` label if you havent got an idea @PooiaFerdowsi .

**Comment by adabadadudu** [comment]
Oh , are you sure that function name is `render` no `Render` ??

It's now new , it's happened for me but I don't know about js . currently I've learn html/css !

So I have some guesses for that error:

The `Uncaught SyntaxError: Cannot use import statement outside a module` error is very readable .

See following dir stuct
```
-module
__libs(html|css|js)
-test
__codes.(html|css|js)
```

**Comment by mehanalavimajd** [comment]
Hello, yeah Render is correct but it again give that error . I didn't understand what u Mean about directory structure

**Comment by adabadadudu** [comment]
if you experience in python , please see following source:

```
-module
__libs.py
-test
__codes.py
```

libs.py:
```py
def somefn():
   ....
```

codes.py:

```py
import ../libs.py
```

now where is `__pycache__` directory ??

**Comment by mehanalavimajd** [comment]
I think  __pycache__ would be in test dir .
But how does this will help in **js** import error?

**Comment by adabadadudu** [comment]
I think python will raise error.

but js is like py in this station

**Comment by mehanalavimajd** [comment]
Hey @PooiaFerdowsi , applecake is going to replace with a new library (look readme) . And I want to suggest some names please if you can 🙏.

**Comment by adabadadudu** [comment]
Unfortunately I am not well for naming.

if it war created by me, I call it jslfw (JavaScriptLittleFrameWork) because I don't have any name for project

**Comment by mehanalavimajd** [comment]
@PooiaFerdowsi I chose panix name for new library and I fix this issue . Would you like to join me at panix (you should know js)?

**Comment by adabadadudu** [comment]
I know primary of javascript and i liket to join

**Comment by mehanalavimajd** [comment]
You are best :)

**Comment by mehanalavimajd** [comment]
please come to [panix library](https://github.com/mehanalavimajd/panix)
