### ISSUE TITLE
Adding events support to applecake

### ISSUE THREAD

**Issue by mehanalavimajd** [applecakejs/applecake#5]
I think  it's very important to add events (like onclick) to applecake . 
Do you agree @PooiaFerdowsi ?

**Comment by adabadadudu** [comment]
are you joking ? so React , Vue don't has events like v-onclick t. the events included from back-end

Yes it's important , I agree

**Comment by mehanalavimajd** [comment]
Ok so one of our goal for 1.0.2 is addings event . 
Thanks @PooiaFerdowsi because helping me in issue and I will be happy if you talk about applecake to others and send PRs . Thanks
